spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/next_events
    username: king-martinien
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 9025

application:
  security:
    jwt:
      expiration: 1
      secret: EY3o41806GnIWOgKpYV3o6CZX9MqPKrZKsuFhKNdc/o=
  mailing:
    frontend:
      activateAccount: http://localhost:8080/activate-account
      resetPassword: http://localhost:8080/reset-password