spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-consumes-media-type: application/json

server:
  servlet:
    context-path: /next-events/api/v1